pipeline:
    name: sweep
    identifier: sweep
    projectIdentifier: tf_provider
    orgIdentifier: Micahs_Projects
    description: Cleans up dangling resources from test runs
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.harnessorg
                repoName: terraform-provider-harness-platform
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheGCS
                                spec:
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                    key: terraform-provider-harness-platform-{{ checksum "go.mod" }}
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    archiveFormat: Gzip
                                name: Restore from cache
                                identifier: Restore_from_cache
                          - step:
                                type: Run
                                name: Install Dependencies
                                identifier: installdependencies
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: go mod vendor
                                    privileged: false
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                          - step:
                                type: SaveCacheGCS
                                spec:
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    key: terraform-provider-harness-platform-{{ checksum "go.mod" }}
                                    sourcePaths:
                                        - ./vendor
                                    archiveFormat: Gzip
                                name: Save cache
                                identifier: Save_cache
                          - step:
                                type: Run
                                name: Build
                                identifier: build
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: go build -v
                                    privileged: false
                                    resources:
                                        limits:
                                            memory: 4Gi
                                            cpu: "1"
                          - step:
                                type: Run
                                name: Test Terraform v1-0-0
                                identifier: Test_Terraform_v100
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: make sweep
                                    privileged: false
                                    envVariables:
                                        TF_ACC: "1"
                                        TF_ACC_TERRAFORM_VERSION: 1.0.0
                                    resources:
                                        limits:
                                            memory: 6Gi
                                            cpu: "2"
                                timeout: 30m
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - AllErrors
                                          action:
                                              type: Ignore
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  sharedPaths:
                      - /goroot
              variables:
                  - name: HARNESS_API_KEY
                    type: Secret
                    value: org.harness_api_key
                  - name: HARNESS_ACCOUNT_ID
                    type: Secret
                    value: org.harness_account_id
                  - name: HARNESS_ENDPOINT
                    type: String
                    value: https://app.harness.io
                  - name: GOPATH
                    type: String
                    value: /goroot
                  - name: TF_ACC
                    type: String
                    value: "1"
                  - name: HARNESS_NG_API_KEY
                    type: Secret
                    value: org.harness_ng_api_key
                  - name: HARNESS_TEST_AWS_ACCESS_KEY_ID
                    type: Secret
                    value: org.aws_access_key_id
                  - name: HARNESS_TEST_AWS_SECRET_ACCESS_KEY
                    type: Secret
                    value: org.aws_secret_access_key
                  - name: HARNESS_TEST_AZURE_CLIENT_ID
                    type: Secret
                    value: org.azure_client_id
                  - name: HARNESS_TEST_AZURE_CLIENT_SECRET
                    type: Secret
                    value: org.azure_client_secret
                  - name: HARNESS_TEST_AZURE_TENANT_ID
                    type: Secret
                    value: org.azure_tenant_id
                  - name: HARNESS_TEST_SPOT_ACCT_ID
                    type: Secret
                    value: org.spotinst_account_id
                  - name: HARNESS_TEST_SPOT_TOKEN
                    type: Secret
                    value: org.spotinst_token
                  - name: HARNESS_DELEGATE_SECRET
                    type: Secret
                    value: org.harness_delegate_secret
                  - name: HARNESS_BEARER_TOKEN
                    type: String
                    value: <+input>
